version: '3.8'

# Docker Compose para infraestructura básica (sin aplicación)
# Usar para: CI/CD, testing, o cuando solo necesites la infraestructura

services:
  postgres:
    image: postgres:15-alpine
    container_name: inventory_postgres
    environment:
      POSTGRES_DB: inventory_system
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - inventory_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U inventory_user -d inventory_system']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: inventory_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - inventory_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  inventory_network:
    driver: bridge
