/** @type {import('jest').Config} */
const config = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src', '<rootDir>/test'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/main.ts',
    '!src/**/*.module.ts',
    '!src/**/index.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  moduleNameMapper: {
    '^@src$': '<rootDir>/src',
    '^@src/(.*)$': '<rootDir>/src/$1',
    '^@auth$': '<rootDir>/src/authentication',
    '^@auth/(.*)$': '<rootDir>/src/authentication/$1',
    '^@user$': '<rootDir>/src/authentication/users',
    '^@user/(.*)$': '<rootDir>/src/authentication/users/$1',
    '^@role$': '<rootDir>/src/authentication/roles',
    '^@role/(.*)$': '<rootDir>/src/authentication/roles/$1',
    '^@session$': '<rootDir>/src/authentication/sessions',
    '^@session/(.*)$': '<rootDir>/src/authentication/sessions/$1',
    '^@security$': '<rootDir>/src/authentication/security',
    '^@security/(.*)$': '<rootDir>/src/authentication/security/$1',
    '^@inventory$': '<rootDir>/src/inventory',
    '^@inventory/(.*)$': '<rootDir>/src/inventory/$1',
    '^@product$': '<rootDir>/src/inventory/products',
    '^@product/(.*)$': '<rootDir>/src/inventory/products/$1',
    '^@warehouse$': '<rootDir>/src/inventory/warehouses',
    '^@warehouse/(.*)$': '<rootDir>/src/inventory/warehouses/$1',
    '^@movement$': '<rootDir>/src/inventory/movements',
    '^@movement/(.*)$': '<rootDir>/src/inventory/movements/$1',
    '^@transfer$': '<rootDir>/src/inventory/transfers',
    '^@transfer/(.*)$': '<rootDir>/src/inventory/transfers/$1',
    '^@stock$': '<rootDir>/src/inventory/stock',
    '^@stock/(.*)$': '<rootDir>/src/inventory/stock/$1',
    '^@sales$': '<rootDir>/src/sales',
    '^@sales/(.*)$': '<rootDir>/src/sales/$1',
    '^@sale$': '<rootDir>/src/sales',
    '^@sale/(.*)$': '<rootDir>/src/sales/$1',
    '^@returns$': '<rootDir>/src/returns',
    '^@returns/(.*)$': '<rootDir>/src/returns/$1',
    '^@return$': '<rootDir>/src/returns',
    '^@return/(.*)$': '<rootDir>/src/returns/$1',
    '^@report$': '<rootDir>/src/report',
    '^@report/(.*)$': '<rootDir>/src/report/$1',
    '^@import$': '<rootDir>/src/import',
    '^@import/(.*)$': '<rootDir>/src/import/$1',
    '^@organization$': '<rootDir>/src/organization',
    '^@organization/(.*)$': '<rootDir>/src/organization/$1',
    '^@application$': '<rootDir>/src/application',
    '^@application/(.*)$': '<rootDir>/src/application/$1',
    '^@infrastructure$': '<rootDir>/src/infrastructure',
    '^@infrastructure/(.*)$': '<rootDir>/src/infrastructure/$1',
    '^@interface$': '<rootDir>/src/interfaces',
    '^@interface/(.*)$': '<rootDir>/src/interfaces/$1',
    '^@shared$': '<rootDir>/src/shared',
    '^@shared/(.*)$': '<rootDir>/src/shared/$1',
    '^@healthCheck$': '<rootDir>/src/healthCheck',
    '^@healthCheck/(.*)$': '<rootDir>/src/healthCheck/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/test/setup.ts'],
  testTimeout: 30000,
  // Additional configurations recommended by the documentation
  clearMocks: true,
  collectCoverage: true,
  coverageThreshold: {
    global: {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90,
    },
  },
  // Configuración para TypeScript
  moduleFileExtensions: ['js', 'json', 'ts'],
  // Transform uuid module (ES modules)
  transformIgnorePatterns: ['node_modules/(?!(uuid|@js-joda)/)'],
  // Transform configuration for ts-jest
  transform: {
    '^.+\\.(t|j)s$': [
      'ts-jest',
      {
        tsconfig: {
          esModuleInterop: true,
          allowSyntheticDefaultImports: true,
        },
      },
    ],
  },
};

module.exports = config;
