/**
 * Centralized Error Codes for the Nevada Inventory System API.
 *
 * Every error response includes an `errorCode` field that the frontend
 * can use to display localized, user-friendly messages.
 *
 * Convention: MODULE_ACTION or MODULE_ENTITY_REASON in UPPER_SNAKE_CASE.
 */

// ─── Authentication ──────────────────────────────────────────────────────────

export const AUTH_AUTHENTICATION_FAILED = 'AUTHENTICATION_ERROR';
export const AUTH_TOKEN_INVALID = 'TOKEN_ERROR';
export const AUTH_RATE_LIMIT = 'RATE_LIMIT_EXCEEDED';
export const AUTH_PASSWORDS_MISMATCH = 'AUTH_PASSWORDS_MISMATCH';
export const AUTH_PASSWORD_REQUIREMENTS = 'AUTH_PASSWORD_REQUIREMENTS';
export const AUTH_PASSWORD_SAME_AS_CURRENT = 'AUTH_PASSWORD_SAME_AS_CURRENT';
export const AUTH_PASSWORD_INCORRECT = 'AUTH_PASSWORD_INCORRECT';
export const AUTH_PASSWORD_CHANGE_FAILED = 'AUTH_PASSWORD_CHANGE_FAILED';
export const AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND';

// ─── Users ───────────────────────────────────────────────────────────────────

export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_VALIDATION_FAILED = 'USER_VALIDATION_FAILED';
export const USER_EMAIL_CONFLICT = 'USER_EMAIL_CONFLICT';
export const USER_USERNAME_CONFLICT = 'USER_USERNAME_CONFLICT';
export const USER_INVALID_STATUS = 'USER_INVALID_STATUS';
export const USER_STATUS_CHANGE_DENIED = 'USER_STATUS_CHANGE_DENIED';
export const USER_ROLE_NOT_FOUND = 'USER_ROLE_NOT_FOUND';
export const USER_ROLE_ORG_MISMATCH = 'USER_ROLE_ORG_MISMATCH';
export const USER_ASSIGNER_NOT_FOUND = 'USER_ASSIGNER_NOT_FOUND';
export const USER_ROLE_ASSIGN_DENIED = 'USER_ROLE_ASSIGN_DENIED';
export const USER_ROLE_ALREADY_ASSIGNED = 'USER_ROLE_ALREADY_ASSIGNED';
export const USER_ROLE_NOT_ASSIGNED = 'USER_ROLE_NOT_ASSIGNED';

// ─── Roles ───────────────────────────────────────────────────────────────────

export const ROLE_NOT_FOUND = 'ROLE_NOT_FOUND';
export const ROLE_ORG_MISMATCH = 'ROLE_ORG_MISMATCH';
export const ROLE_NAME_TOO_SHORT = 'ROLE_NAME_TOO_SHORT';
export const ROLE_NAME_TOO_LONG = 'ROLE_NAME_TOO_LONG';
export const ROLE_NAME_SYSTEM_CONFLICT = 'ROLE_NAME_SYSTEM_CONFLICT';
export const ROLE_NAME_ORG_CONFLICT = 'ROLE_NAME_ORG_CONFLICT';
export const ROLE_SYSTEM_IMMUTABLE = 'ROLE_SYSTEM_IMMUTABLE';
export const ROLE_DESCRIPTION_TOO_LONG = 'ROLE_DESCRIPTION_TOO_LONG';
export const ROLE_DELETE_DENIED = 'ROLE_DELETE_DENIED';
export const ROLE_ID_REQUIRED = 'ROLE_ID_REQUIRED';
export const ROLE_ORG_ID_REQUIRED = 'ROLE_ORG_ID_REQUIRED';
export const ROLE_PERMISSIONS_REQUIRED = 'ROLE_PERMISSIONS_REQUIRED';
export const ROLE_PERMISSIONS_NOT_FOUND = 'ROLE_PERMISSIONS_NOT_FOUND';

// ─── Products ────────────────────────────────────────────────────────────────

export const PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND';
export const PRODUCT_SKU_CONFLICT = 'PRODUCT_SKU_CONFLICT';
export const PRODUCT_CREATION_ERROR = 'PRODUCT_CREATION_ERROR';
export const PRODUCT_UPDATE_ERROR = 'PRODUCT_UPDATE_ERROR';
export const PRODUCT_STATUS_CHANGE_DENIED = 'PRODUCT_STATUS_CHANGE_DENIED';
export const PRODUCT_COST_METHOD_IMMUTABLE = 'PRODUCT_COST_METHOD_IMMUTABLE';

// ─── Categories ──────────────────────────────────────────────────────────────

export const CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND';
export const CATEGORY_PARENT_NOT_FOUND = 'CATEGORY_PARENT_NOT_FOUND';
export const CATEGORY_SELF_PARENT = 'CATEGORY_SELF_PARENT';
export const CATEGORY_NAME_CONFLICT = 'CATEGORY_NAME_CONFLICT';
export const CATEGORY_HAS_CHILDREN = 'CATEGORY_HAS_CHILDREN';
export const CATEGORY_HAS_PRODUCTS = 'CATEGORY_HAS_PRODUCTS';
export const CATEGORY_DELETE_ERROR = 'CATEGORY_DELETE_ERROR';
export const CATEGORY_CREATION_ERROR = 'CATEGORY_CREATION_ERROR';
export const CATEGORY_UPDATE_ERROR = 'CATEGORY_UPDATE_ERROR';
export const CATEGORY_INVALID_PARENT_REF = 'CATEGORY_INVALID_PARENT_REF';
export const CATEGORY_REFERENCED_NOT_FOUND = 'CATEGORY_REFERENCED_NOT_FOUND';

// ─── Warehouses ──────────────────────────────────────────────────────────────

export const WAREHOUSE_NOT_FOUND = 'WAREHOUSE_NOT_FOUND';
export const WAREHOUSE_CODE_CONFLICT = 'WAREHOUSE_CODE_CONFLICT';
export const WAREHOUSE_HAS_STOCK = 'WAREHOUSE_HAS_STOCK';
export const WAREHOUSE_UPDATE_ERROR = 'WAREHOUSE_UPDATE_ERROR';

// ─── Stock ───────────────────────────────────────────────────────────────────

export const STOCK_NOT_FOUND = 'STOCK_NOT_FOUND';
export const STOCK_INSUFFICIENT = 'INSUFFICIENT_STOCK';

// ─── Movements ───────────────────────────────────────────────────────────────

export const MOVEMENT_NOT_FOUND = 'MOVEMENT_NOT_FOUND';
export const MOVEMENT_CANNOT_POST = 'MOVEMENT_CANNOT_POST';
export const MOVEMENT_CREATION_ERROR = 'MOVEMENT_CREATION_ERROR';
export const MOVEMENT_CANNOT_BE_UPDATED = 'MOVEMENT_CANNOT_BE_UPDATED';
export const MOVEMENT_UPDATE_ERROR = 'MOVEMENT_UPDATE_ERROR';
export const MOVEMENT_CANNOT_BE_DELETED = 'MOVEMENT_CANNOT_BE_DELETED';
export const MOVEMENT_CANNOT_BE_VOIDED = 'MOVEMENT_CANNOT_BE_VOIDED';
export const MOVEMENT_CANNOT_BE_RETURNED = 'MOVEMENT_CANNOT_BE_RETURNED';
export const MOVEMENT_RETURN_ERROR = 'MOVEMENT_RETURN_ERROR';

// ─── Transfers ───────────────────────────────────────────────────────────────

export const TRANSFER_NOT_FOUND = 'TRANSFER_NOT_FOUND';
export const TRANSFER_VALIDATION_FAILED = 'TRANSFER_VALIDATION_FAILED';
export const TRANSFER_LINES_INVALID = 'TRANSFER_LINES_INVALID';
export const TRANSFER_INSUFFICIENT_STOCK = 'TRANSFER_INSUFFICIENT_STOCK';
export const TRANSFER_LOCATION_INVALID = 'TRANSFER_LOCATION_INVALID';
export const TRANSFER_CANNOT_CONFIRM = 'TRANSFER_CANNOT_CONFIRM';
export const TRANSFER_CANNOT_RECEIVE = 'TRANSFER_CANNOT_RECEIVE';
export const TRANSFER_CANNOT_REJECT = 'TRANSFER_CANNOT_REJECT';
export const TRANSFER_CANNOT_CANCEL = 'TRANSFER_CANNOT_CANCEL';

// ─── Sales ───────────────────────────────────────────────────────────────────

export const SALE_NOT_FOUND = 'SALE_NOT_FOUND';
export const SALE_CREATION_ERROR = 'SALE_CREATION_ERROR';
export const SALE_INSUFFICIENT_STOCK = 'SALE_INSUFFICIENT_STOCK';
export const SALE_LINE_PRODUCT_NOT_FOUND = 'SALE_LINE_PRODUCT_NOT_FOUND';
export const SALE_SWAP_PRICE_REQUIRED = 'SALE_SWAP_PRICE_REQUIRED';
export const SALE_SWAP_DENIED = 'SALE_SWAP_DENIED';
export const SALE_PICKING_NOT_ENABLED = 'SALE_PICKING_NOT_ENABLED';
export const SALE_SHIPPING_NOT_ENABLED = 'SALE_SHIPPING_NOT_ENABLED';
export const SALE_CANCEL_ERROR = 'SALE_CANCEL_ERROR';
export const SALE_COMPLETE_ERROR = 'SALE_COMPLETE_ERROR';
export const SALE_SHIPPING_ERROR = 'SALE_SHIPPING_ERROR';
export const SALE_RETURN_ERROR = 'SALE_RETURN_ERROR';

// ─── Returns ─────────────────────────────────────────────────────────────────

export const RETURN_NOT_FOUND = 'RETURN_NOT_FOUND';
export const RETURN_WAREHOUSE_NOT_FOUND = 'RETURN_WAREHOUSE_NOT_FOUND';
export const RETURN_SALE_ID_REQUIRED = 'RETURN_SALE_ID_REQUIRED';
export const RETURN_MOVEMENT_ID_REQUIRED = 'RETURN_MOVEMENT_ID_REQUIRED';
export const RETURN_PRODUCT_NOT_FOUND = 'RETURN_PRODUCT_NOT_FOUND';
export const RETURN_SALE_NOT_FOUND = 'RETURN_SALE_NOT_FOUND';
export const RETURN_LINE_VALIDATION_FAILED = 'RETURN_LINE_VALIDATION_FAILED';
export const RETURN_CONFIRMATION_FAILED = 'RETURN_CONFIRMATION_FAILED';
export const RETURN_CANCEL_ERROR = 'RETURN_CANCEL_ERROR';
export const RETURN_ORIGINAL_PRICE_REQUIRED = 'RETURN_ORIGINAL_PRICE_REQUIRED';
export const RETURN_ORIGINAL_COST_REQUIRED = 'RETURN_ORIGINAL_COST_REQUIRED';

// ─── Reports ─────────────────────────────────────────────────────────────────

export const REPORT_INVALID_TYPE = 'REPORT_INVALID_TYPE';
export const REPORT_TEMPLATE_NOT_FOUND = 'REPORT_TEMPLATE_NOT_FOUND';
export const REPORT_TEMPLATE_NAME_TOO_SHORT = 'REPORT_TEMPLATE_NAME_TOO_SHORT';
export const REPORT_TEMPLATE_NAME_TOO_LONG = 'REPORT_TEMPLATE_NAME_TOO_LONG';
export const REPORT_TEMPLATE_NAME_CONFLICT = 'REPORT_TEMPLATE_NAME_CONFLICT';
export const REPORT_GENERATION_ERROR = 'REPORT_GENERATION_ERROR';
export const REPORT_TEMPLATE_CREATION_ERROR = 'REPORT_TEMPLATE_CREATION_ERROR';
export const REPORT_TEMPLATE_UPDATE_ERROR = 'REPORT_TEMPLATE_UPDATE_ERROR';

// ─── Companies ───────────────────────────────────────────────────────────────

export const COMPANY_NOT_FOUND = 'COMPANY_NOT_FOUND';
export const COMPANY_DELETE_ERROR = 'COMPANY_DELETE_ERROR';
export const COMPANY_CODE_CONFLICT = 'COMPANY_CODE_CONFLICT';
export const COMPANY_NAME_CONFLICT = 'COMPANY_NAME_CONFLICT';
export const COMPANY_CONFLICT = 'COMPANY_CONFLICT';
export const COMPANY_CREATION_ERROR = 'COMPANY_CREATION_ERROR';
export const COMPANY_UPDATE_ERROR = 'COMPANY_UPDATE_ERROR';
export const COMPANY_HAS_PRODUCTS = 'COMPANY_HAS_PRODUCTS';

// ─── Organizations ───────────────────────────────────────────────────────────

export const ORG_NOT_FOUND = 'ORG_NOT_FOUND';
export const ORG_SLUG_INVALID = 'ORG_SLUG_INVALID';
export const ORG_SLUG_CONFLICT = 'ORG_SLUG_CONFLICT';
export const ORG_NAME_CONFLICT = 'ORG_NAME_CONFLICT';
export const ORG_CREATION_ERROR = 'ORG_CREATION_ERROR';

// ─── Imports ─────────────────────────────────────────────────────────────────

export const IMPORT_BATCH_NOT_FOUND = 'IMPORT_BATCH_NOT_FOUND';
export const IMPORT_INVALID_TYPE = 'IMPORT_INVALID_TYPE';
export const IMPORT_FILE_VALIDATION_FAILED = 'IMPORT_FILE_VALIDATION_FAILED';
export const IMPORT_STRUCTURE_INVALID = 'IMPORT_STRUCTURE_INVALID';
export const IMPORT_NOT_VALIDATED = 'IMPORT_NOT_VALIDATED';
export const IMPORT_FILE_NAME_REQUIRED = 'IMPORT_FILE_NAME_REQUIRED';
export const IMPORT_BATCH_CREATION_FAILED = 'IMPORT_BATCH_CREATION_FAILED';
export const IMPORT_TEMPLATE_FAILED = 'IMPORT_TEMPLATE_FAILED';
export const IMPORT_ERROR_REPORT_FAILED = 'IMPORT_ERROR_REPORT_FAILED';
export const IMPORT_EXECUTION_FAILED = 'IMPORT_EXECUTION_FAILED';
export const IMPORT_PREVIEW_ERROR = 'IMPORT_PREVIEW_ERROR';
export const IMPORT_PROCESSING_ERROR = 'IMPORT_PROCESSING_ERROR';
export const IMPORT_VALIDATION_ERROR = 'IMPORT_VALIDATION_ERROR';

// ─── Dashboard ───────────────────────────────────────────────────────────────

export const DASHBOARD_METRICS_FAILED = 'DASHBOARD_METRICS_FAILED';

// ─── Audit ───────────────────────────────────────────────────────────────────

export const AUDIT_LOG_NOT_FOUND = 'AUDIT_LOG_NOT_FOUND';

// ─── Reorder Rules ───────────────────────────────────────────────────────────

export const REORDER_RULE_NOT_FOUND = 'REORDER_RULE_NOT_FOUND';
export const REORDER_RULE_INVALID_QUANTITIES = 'REORDER_RULE_INVALID_QUANTITIES';
export const REORDER_RULE_CONFLICT = 'REORDER_RULE_CONFLICT';
export const REORDER_RULE_CREATION_ERROR = 'REORDER_RULE_CREATION_ERROR';
export const REORDER_RULE_UPDATE_ERROR = 'REORDER_RULE_UPDATE_ERROR';
export const REORDER_RULE_DELETE_ERROR = 'REORDER_RULE_DELETE_ERROR';

// ─── Generic ─────────────────────────────────────────────────────────────────

export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const UNKNOWN_ERROR = 'UNKNOWN_ERROR';
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
