import { PrismaClient } from '@infrastructure/database/generated/prisma';
import { IProduct } from '@shared/types/database.types';

interface CategoryRecord {
  id: string;
  name: string;
}

interface ProductDef {
  sku: string;
  name: string;
  description: string;
  unit: string;
  barcode: string;
  brand: string;
  model: string;
  price: number;
  costMethod: string;
  isActive: boolean;
  categoryName: string;
}

// 50 products across all categories
const PRODUCTS: ProductDef[] = [
  // === Computadores (6) ===
  {
    sku: 'LAP-DELL-001',
    name: 'Laptop Dell XPS 15',
    description: 'Laptop ultrabook 15.6" Intel Core i7-13700H, 16GB RAM, 512GB SSD',
    unit: 'UND',
    barcode: '7701234567001',
    brand: 'Dell',
    model: 'XPS 15 9530',
    price: 5499000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Computadores',
  },
  {
    sku: 'LAP-LENOVO-001',
    name: 'Laptop Lenovo ThinkPad T14',
    description: 'Laptop empresarial 14" AMD Ryzen 7 PRO, 16GB RAM, 256GB SSD',
    unit: 'UND',
    barcode: '7701234567002',
    brand: 'Lenovo',
    model: 'ThinkPad T14 Gen 4',
    price: 4299000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Computadores',
  },
  {
    sku: 'LAP-HP-001',
    name: 'HP ProBook 450 G10',
    description: 'Laptop profesional 15.6" Intel Core i5-1335U, 8GB RAM, 256GB SSD',
    unit: 'UND',
    barcode: '7701234567003',
    brand: 'HP',
    model: 'ProBook 450 G10',
    price: 3199000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Computadores',
  },
  {
    sku: 'TAB-APPLE-001',
    name: 'iPad Air M2',
    description: 'Tablet Apple iPad Air 11" M2, 128GB, Wi-Fi',
    unit: 'UND',
    barcode: '7701234567004',
    brand: 'Apple',
    model: 'iPad Air M2 2024',
    price: 3299000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Computadores',
  },
  {
    sku: 'LAP-ACER-001',
    name: 'Acer Aspire 5 A515',
    description: 'Laptop 15.6" Intel Core i5-1235U, 8GB RAM, 512GB SSD',
    unit: 'UND',
    barcode: '7701234567005',
    brand: 'Acer',
    model: 'Aspire 5 A515-57',
    price: 2599000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Computadores',
  },
  {
    sku: 'DT-DELL-001',
    name: 'Dell OptiPlex 7010 SFF',
    description: 'Desktop Intel Core i5-13500, 8GB RAM, 256GB SSD',
    unit: 'UND',
    barcode: '7701234567006',
    brand: 'Dell',
    model: 'OptiPlex 7010',
    price: 3899000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Computadores',
  },

  // === Periféricos (9) ===
  {
    sku: 'MOUSE-LOG-001',
    name: 'Mouse Logitech MX Master 3S',
    description: 'Mouse inalámbrico ergonómico con sensor 8000 DPI',
    unit: 'UND',
    barcode: '7701234567010',
    brand: 'Logitech',
    model: 'MX Master 3S',
    price: 449000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Periféricos',
  },
  {
    sku: 'MOUSE-LOG-002',
    name: 'Mouse Logitech M185',
    description: 'Mouse inalámbrico compacto y económico',
    unit: 'UND',
    barcode: '7701234567011',
    brand: 'Logitech',
    model: 'M185',
    price: 59000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Periféricos',
  },
  {
    sku: 'MOUSE-RAZ-001',
    name: 'Mouse Razer DeathAdder V3',
    description: 'Mouse gaming ergonómico sensor 30K DPI',
    unit: 'UND',
    barcode: '7701234567017',
    brand: 'Razer',
    model: 'DeathAdder V3',
    price: 349000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Periféricos',
  },
  {
    sku: 'KB-LOG-001',
    name: 'Teclado Logitech MX Keys S',
    description: 'Teclado inalámbrico retroiluminado para productividad',
    unit: 'UND',
    barcode: '7701234567012',
    brand: 'Logitech',
    model: 'MX Keys S',
    price: 549000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Periféricos',
  },
  {
    sku: 'KB-MECH-001',
    name: 'Teclado Mecánico Keychron K2',
    description: 'Teclado mecánico 75% Bluetooth, switches Gateron Brown',
    unit: 'UND',
    barcode: '7701234567013',
    brand: 'Keychron',
    model: 'K2 V2',
    price: 389000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Periféricos',
  },
  {
    sku: 'WEBCAM-LOG-001',
    name: 'Webcam Logitech C920s HD Pro',
    description: 'Webcam Full HD 1080p con obturador de privacidad',
    unit: 'UND',
    barcode: '7701234567014',
    brand: 'Logitech',
    model: 'C920s',
    price: 329000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Periféricos',
  },
  {
    sku: 'HEADSET-001',
    name: 'Headset Jabra Evolve2 55',
    description: 'Auriculares inalámbricos con cancelación de ruido para oficina',
    unit: 'UND',
    barcode: '7701234567015',
    brand: 'Jabra',
    model: 'Evolve2 55',
    price: 799000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Periféricos',
  },
  {
    sku: 'HEADSET-002',
    name: 'Audífonos HyperX Cloud III',
    description: 'Auriculares gaming con micrófono desmontable',
    unit: 'UND',
    barcode: '7701234567016',
    brand: 'HyperX',
    model: 'Cloud III',
    price: 399000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Periféricos',
  },
  {
    sku: 'PARLANTE-001',
    name: 'Parlante JBL Flip 6',
    description: 'Parlante Bluetooth portátil resistente al agua IP67',
    unit: 'UND',
    barcode: '7701234567018',
    brand: 'JBL',
    model: 'Flip 6',
    price: 479000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Periféricos',
  },

  // === Monitores (5) ===
  {
    sku: 'MON-LG-001',
    name: 'Monitor LG UltraWide 34"',
    description: 'Monitor 34" IPS QHD 3440x1440 USB-C, 60Hz',
    unit: 'UND',
    barcode: '7701234567020',
    brand: 'LG',
    model: '34WP65C-B',
    price: 1899000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Monitores',
  },
  {
    sku: 'MON-DELL-001',
    name: 'Monitor Dell 27" 4K',
    description: 'Monitor 27" IPS 4K UHD, USB-C Hub, 60Hz',
    unit: 'UND',
    barcode: '7701234567021',
    brand: 'Dell',
    model: 'U2723QE',
    price: 2199000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Monitores',
  },
  {
    sku: 'MON-SAM-001',
    name: 'Monitor Samsung 24" FHD',
    description: 'Monitor 24" IPS FHD 1080p, ajuste de altura',
    unit: 'UND',
    barcode: '7701234567022',
    brand: 'Samsung',
    model: 'S24C430',
    price: 749000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Monitores',
  },
  {
    sku: 'MON-LG-002',
    name: 'Monitor LG 27" QHD 144Hz',
    description: 'Monitor gaming 27" IPS QHD 2560x1440 144Hz',
    unit: 'UND',
    barcode: '7701234567023',
    brand: 'LG',
    model: '27GP850-B',
    price: 1599000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Monitores',
  },
  {
    sku: 'MON-BNQ-001',
    name: 'Monitor BenQ GW2480',
    description: 'Monitor 24" IPS FHD Eye-Care, sin parpadeo',
    unit: 'UND',
    barcode: '7701234567024',
    brand: 'BenQ',
    model: 'GW2480',
    price: 689000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Monitores',
  },

  // === Almacenamiento (5) ===
  {
    sku: 'SSD-SAM-001',
    name: 'SSD Samsung 870 EVO 1TB',
    description: 'Disco de estado sólido SATA III 2.5", lectura 560MB/s',
    unit: 'UND',
    barcode: '7701234567030',
    brand: 'Samsung',
    model: '870 EVO',
    price: 369000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Almacenamiento',
  },
  {
    sku: 'SSD-NVME-001',
    name: 'SSD NVMe Samsung 980 PRO 1TB',
    description: 'SSD M.2 NVMe PCIe 4.0, lectura 7000MB/s',
    unit: 'UND',
    barcode: '7701234567033',
    brand: 'Samsung',
    model: '980 PRO',
    price: 549000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Almacenamiento',
  },
  {
    sku: 'HDD-EXT-001',
    name: 'Disco Externo Seagate 2TB',
    description: 'Disco duro externo portátil USB 3.0',
    unit: 'UND',
    barcode: '7701234567031',
    brand: 'Seagate',
    model: 'Expansion 2TB',
    price: 259000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Almacenamiento',
  },
  {
    sku: 'USB-SAN-001',
    name: 'USB Kingston DataTraveler 64GB',
    description: 'Memoria USB 3.2 Gen 1, lectura 200MB/s',
    unit: 'UND',
    barcode: '7701234567032',
    brand: 'Kingston',
    model: 'DataTraveler Exodia',
    price: 35000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Almacenamiento',
  },
  {
    sku: 'MICROSD-001',
    name: 'MicroSD Samsung EVO Plus 128GB',
    description: 'Tarjeta microSD UHS-I U3 A2 V30, lectura 160MB/s',
    unit: 'UND',
    barcode: '7701234567034',
    brand: 'Samsung',
    model: 'EVO Plus 128GB',
    price: 65000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Almacenamiento',
  },

  // === Cables (4) ===
  {
    sku: 'CABLE-HDMI-001',
    name: 'Cable HDMI 2.1 - 2m',
    description: 'Cable HDMI Ultra High Speed 48Gbps, soporte 8K',
    unit: 'UND',
    barcode: '7701234567040',
    brand: 'Ugreen',
    model: 'HD140',
    price: 49000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Cables',
  },
  {
    sku: 'CABLE-USBC-001',
    name: 'Cable USB-C a USB-C 1m',
    description: 'Cable USB-C 3.2 Gen 2, carga 100W, datos 10Gbps',
    unit: 'UND',
    barcode: '7701234567041',
    brand: 'Anker',
    model: 'A8486',
    price: 59000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Cables',
  },
  {
    sku: 'CABLE-ETH-001',
    name: 'Cable Ethernet Cat6 - 3m',
    description: 'Cable de red Cat6 UTP 1Gbps',
    unit: 'UND',
    barcode: '7701234567042',
    brand: 'Nexxt',
    model: 'Cat6 UTP',
    price: 15000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Cables',
  },
  {
    sku: 'CABLE-DP-001',
    name: 'Cable DisplayPort 1.4 - 2m',
    description: 'Cable DP 1.4 HBR3, soporte 8K@60Hz, 4K@144Hz',
    unit: 'UND',
    barcode: '7701234567043',
    brand: 'Ugreen',
    model: 'DP114',
    price: 55000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Cables',
  },

  // === Routers y Switches (3) ===
  {
    sku: 'RTR-TPLINK-001',
    name: 'Router TP-Link Archer AX55',
    description: 'Router Wi-Fi 6 AX3000 Dual Band, MU-MIMO',
    unit: 'UND',
    barcode: '7701234567050',
    brand: 'TP-Link',
    model: 'Archer AX55',
    price: 399000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Routers y Switches',
  },
  {
    sku: 'SW-TPLINK-001',
    name: 'Switch TP-Link 8 puertos Gigabit',
    description: 'Switch no administrable 8 puertos 10/100/1000 Mbps',
    unit: 'UND',
    barcode: '7701234567051',
    brand: 'TP-Link',
    model: 'TL-SG108',
    price: 129000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Routers y Switches',
  },
  {
    sku: 'AP-UBIQ-001',
    name: 'Ubiquiti UniFi AP AC Lite',
    description: 'Access Point Wi-Fi 5 dual-band, PoE, 1167 Mbps',
    unit: 'UND',
    barcode: '7701234567052',
    brand: 'Ubiquiti',
    model: 'UAP-AC-LITE',
    price: 459000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Routers y Switches',
  },

  // === Adaptadores (2) ===
  {
    sku: 'HUB-USBC-001',
    name: 'Hub USB-C 7 en 1',
    description: 'Hub USB-C con HDMI 4K, 3xUSB-A, SD, microSD, PD 100W',
    unit: 'UND',
    barcode: '7701234567055',
    brand: 'Ugreen',
    model: 'CM511',
    price: 189000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Adaptadores',
  },
  {
    sku: 'DOCK-001',
    name: 'Docking Station USB-C Triple Display',
    description: 'Dock USB-C con 2xHDMI, DP, 4xUSB-A, Ethernet, PD 100W',
    unit: 'UND',
    barcode: '7701234567056',
    brand: 'CalDigit',
    model: 'TS4',
    price: 1299000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Adaptadores',
  },

  // === Fundas y Estuches (1) ===
  {
    sku: 'FUNDA-LAP-001',
    name: 'Funda Laptop 15.6" Neopreno',
    description: 'Funda protectora de neopreno resistente al agua',
    unit: 'UND',
    barcode: '7701234567060',
    brand: 'Tomtoc',
    model: 'A13-E02D',
    price: 89000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Fundas y Estuches',
  },

  // === Cargadores (2) ===
  {
    sku: 'CHRG-USBC-001',
    name: 'Cargador USB-C 65W GaN',
    description: 'Cargador rápido GaN, 2x USB-C + 1x USB-A',
    unit: 'UND',
    barcode: '7701234567065',
    brand: 'Anker',
    model: 'Nano II 65W',
    price: 179000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Cargadores',
  },
  {
    sku: 'PBANK-001',
    name: 'Power Bank 20000mAh',
    description: 'Batería externa 20000mAh con carga rápida USB-C PD 22.5W',
    unit: 'UND',
    barcode: '7701234567066',
    brand: 'Xiaomi',
    model: 'Mi Power Bank 3',
    price: 149000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Cargadores',
  },

  // === Soportes (2) ===
  {
    sku: 'SOPORTE-LAP-001',
    name: 'Soporte Laptop Aluminio',
    description: 'Soporte ergonómico plegable de aluminio para laptop',
    unit: 'UND',
    barcode: '7701234567070',
    brand: 'Rain Design',
    model: 'mStand',
    price: 249000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Soportes',
  },
  {
    sku: 'BRAZO-MON-001',
    name: 'Brazo Monitor Articulado',
    description: 'Brazo articulado para monitor 17-32", VESA 100x100',
    unit: 'UND',
    barcode: '7701234567071',
    brand: 'Ergotron',
    model: 'LX Desk Mount',
    price: 599000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Soportes',
  },

  // === Impresoras (3) ===
  {
    sku: 'IMP-HP-001',
    name: 'Impresora HP LaserJet Pro M404dn',
    description: 'Impresora láser monocromática, dúplex automático, red',
    unit: 'UND',
    barcode: '7701234567080',
    brand: 'HP',
    model: 'LaserJet Pro M404dn',
    price: 1299000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Impresoras',
  },
  {
    sku: 'IMP-EPSON-001',
    name: 'Impresora Epson EcoTank L3250',
    description: 'Impresora multifuncional con tanque de tinta Wi-Fi',
    unit: 'UND',
    barcode: '7701234567081',
    brand: 'Epson',
    model: 'EcoTank L3250',
    price: 749000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Impresoras',
  },
  {
    sku: 'IMP-BRO-001',
    name: 'Impresora Brother MFC-L2710DW',
    description: 'Multifuncional láser monocromática con ADF, dúplex, Wi-Fi',
    unit: 'UND',
    barcode: '7701234567082',
    brand: 'Brother',
    model: 'MFC-L2710DW',
    price: 999000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Impresoras',
  },

  // === Tóner y Tintas (2) ===
  {
    sku: 'TONER-HP-001',
    name: 'Tóner HP 58A Negro',
    description: 'Tóner original HP LaserJet 58A (CF258A), 3000 páginas',
    unit: 'UND',
    barcode: '7701234567085',
    brand: 'HP',
    model: 'CF258A',
    price: 289000,
    costMethod: 'FIFO',
    isActive: true,
    categoryName: 'Tóner y Tintas',
  },
  {
    sku: 'TINTA-EPSON-001',
    name: 'Tinta Epson 544 Pack 4 colores',
    description: 'Pack de 4 botellas de tinta (negro, cian, magenta, amarillo)',
    unit: 'KIT',
    barcode: '7701234567086',
    brand: 'Epson',
    model: 'T544',
    price: 109000,
    costMethod: 'FIFO',
    isActive: true,
    categoryName: 'Tóner y Tintas',
  },

  // === Papel (1) ===
  {
    sku: 'PAPEL-A4-001',
    name: 'Resma Papel A4 75g',
    description: 'Resma de 500 hojas papel bond blanco 75g/m²',
    unit: 'RESMA',
    barcode: '7701234567090',
    brand: 'Reprograf',
    model: 'Multifuncional A4',
    price: 16000,
    costMethod: 'FIFO',
    isActive: true,
    categoryName: 'Papel',
  },

  // === Software y Licencias (3) ===
  {
    sku: 'LIC-M365-001',
    name: 'Microsoft 365 Business Basic',
    description: 'Licencia anual Microsoft 365 por usuario',
    unit: 'LIC',
    barcode: '7701234567095',
    brand: 'Microsoft',
    model: 'M365 Business Basic',
    price: 288000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Software y Licencias',
  },
  {
    sku: 'LIC-ADOBE-001',
    name: 'Adobe Creative Cloud',
    description: 'Licencia anual Adobe CC All Apps',
    unit: 'LIC',
    barcode: '7701234567096',
    brand: 'Adobe',
    model: 'Creative Cloud All Apps',
    price: 1800000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Software y Licencias',
  },
  {
    sku: 'LIC-WIN11-001',
    name: 'Windows 11 Pro OEM',
    description: 'Licencia OEM Windows 11 Professional 64-bit',
    unit: 'LIC',
    barcode: '7701234567097',
    brand: 'Microsoft',
    model: 'Win11 Pro OEM',
    price: 699000,
    costMethod: 'AVG',
    isActive: true,
    categoryName: 'Software y Licencias',
  },

  // === Inactive products (2) ===
  {
    sku: 'DISC-OLD-001',
    name: 'Disco DVD-RW 4.7GB (Descontinuado)',
    description: 'Discos DVD regrabables - producto descontinuado',
    unit: 'PACK',
    barcode: '7701234567099',
    brand: 'Verbatim',
    model: 'DVD-RW 4.7GB',
    price: 25000,
    costMethod: 'AVG',
    isActive: false,
    categoryName: 'Almacenamiento',
  },
  {
    sku: 'IMP-DOT-001',
    name: 'Impresora Epson LX-350 Matricial (Descontinuado)',
    description: 'Impresora matricial de impacto - descontinuada',
    unit: 'UND',
    barcode: '7701234567098',
    brand: 'Epson',
    model: 'LX-350',
    price: 899000,
    costMethod: 'AVG',
    isActive: false,
    categoryName: 'Impresoras',
  },
];

export class DemoProductsSeed {
  constructor(private prisma: PrismaClient) {}

  async seed(orgId: string, categories: CategoryRecord[]): Promise<IProduct[]> {
    const categoryMap = new Map(categories.map(c => [c.name, c.id]));
    const products: IProduct[] = [];

    for (const prodDef of PRODUCTS) {
      const { categoryName, ...prodData } = prodDef;

      const product = await this.prisma.product.upsert({
        where: { sku_orgId: { sku: prodData.sku, orgId } },
        update: {},
        create: {
          ...prodData,
          currency: 'COP',
          orgId,
        },
      });

      // Link to category
      const categoryId = categoryMap.get(categoryName);
      if (categoryId) {
        const existing = await this.prisma.product.findUnique({
          where: { id: product.id },
          include: { categories: { where: { id: categoryId } } },
        });
        if (existing && existing.categories.length === 0) {
          await this.prisma.product.update({
            where: { id: product.id },
            data: { categories: { connect: { id: categoryId } } },
          });
        }
      }

      const productWithNumberPrice = {
        ...product,
        price: product.price
          ? typeof product.price === 'object' && 'toNumber' in product.price
            ? (product.price as { toNumber(): number }).toNumber()
            : product.price
          : 0,
      };
      products.push(productWithNumberPrice as unknown as IProduct);
    }

    return products;
  }
}
